Repository jupyterlab/jupyterlab-git, pull requests merged in 2019-12, with the labels that each got.

#469 Fixes #460: better handling of branch edge cases
  jupyterlab_git/git.py
  jupyterlab_git/tests/test_branch.py
Labels: pkg:Server Extension, type:Bug

#459 Update refresh interval
  schema/plugin.json
  src/index.ts
  src/model.ts
Labels: pkg:Frontend, type:Enhancement

#478 followup #448: fix git add multiple files
  jupyterlab_git/git.py
Labels: pkg:Server Extension, type:Bug

#477 followup #450: fixes behavior when `"disableBranchWithChanges": true`
  src/components/BranchHeader.tsx
  src/components/GitPanel.tsx
Labels: pkg:Frontend, type:Bug

#479 bump to `0.10.0` for dev branch; final `0.9.0` release system fixes
  jupyterlab_git/_version.py
  package.json
  release.py
Labels: type:Maintenance

#475 Use standard unittest and not mock
  .gitignore
  jupyterlab_git/git.py
  jupyterlab_git/tests/test_branch.py
  jupyterlab_git/tests/test_clone.py
  jupyterlab_git/tests/test_config.py
  jupyterlab_git/tests/test_detailed_log.py
  jupyterlab_git/tests/test_diff.py
  jupyterlab_git/tests/test_handlers.py
  jupyterlab_git/tests/test_pushpull.py
Labels: pkg:Server Extension, type:Maintenance

#486 Reorganize model
  src/model.ts
  src/tokens.ts
Labels: pkg:Frontend, type:Maintenance

#465 Adjust branch dropdown alignment
  src/style/BranchHeaderStyle.ts
Labels: pkg:Frontend, type:Styling Defect

#488 Remove unused svg files
  style/images/author.svg
  style/images/branch.svg
  style/images/caretdownwhite.svg
  style/images/caretrightwhite.svg
  style/images/deletion-color.svg
  style/images/deletion-white.svg
  style/images/directory-white.svg
  style/images/directory.svg
  style/images/edit-circle-active.svg
  style/images/edit-circle-selected-active.svg
  style/images/edit-circle-selected.svg
  style/images/edit-circle.svg
  style/images/fade-left.svg
  style/images/fade-right.svg
  style/images/git-clone-icon-disabled.svg
  style/images/head-circle-active.svg
  style/images/head-circle-selected-active.svg
  style/images/head-circle-selected.svg
  style/images/head-circle.svg
  style/images/home.svg
  style/images/icon-branch-tracking.svg
  style/images/left-arrow.svg
  style/images/normal-circle-active.svg
  style/images/normal-circle-selected-active.svg
  style/images/normal-circle-selected.svg
  style/images/normal-circle.svg
  style/images/path-arrow-right.svg
  style/images/refresh-hover.svg
  style/images/refresh.svg
  style/images/reset-white.svg
  style/images/reset.svg
  style/images/right-arrow.svg
  style/images/track.svg
  style/images/triangle-down-white.svg
  style/images/triangle-down.svg
  style/images/triangle-right-white.svg
  style/images/triangle-right.svg
  style/variables.css
Labels: type:Maintenance

#480 resizable commit message input box
  package.json
  src/components/CommitBox.tsx
  src/components/FileList.tsx
  src/style/BranchHeaderStyle.ts
  src/style/GitStageStyle.ts
  src/style/GitWidgetStyle.ts
  tests/test-components/CommitBox.spec.tsx
  yarn.lock
Labels: pkg:Frontend, type:Enhancement

#490 Use ServerTest for handler testing
  jupyterlab_git/git.py
  jupyterlab_git/handlers.py
  jupyterlab_git/tests/test_config.py
  jupyterlab_git/tests/test_handlers.py
Labels: type:Maintenance

#467 Set title attributes to support tooltip info
  src/components/SinglePastCommitInfo.tsx
Labels: pkg:Frontend, type:Enhancement
