Repository jupyterlab/jupyterlab-git, pull requests merged in 2020-01, with the labels that each got.

#510 Refactor commit box
  src/components/CommitBox.tsx
  src/components/FileList.tsx
  src/components/GitPanel.tsx
  src/style/BranchHeaderStyle.ts
  src/style/CommitBox.ts
  tests/test-components/CommitBox.spec.tsx
  tests/test-components/GitPanel.spec.tsx
Labels: pkg:Frontend, tag:Design and UX, type:Enhancement

#506 Fix multiline Git options interpretation
  jupyterlab_git/git.py
  jupyterlab_git/tests/test_config.py
Labels: pkg:Frontend, type:Bug

#507 Format root directory folder as posix
  jupyterlab_git/handlers.py
Labels: pkg:Frontend, type:Bug

#511 Switch branch header tab order
  src/components/BranchHeader.tsx
Labels: pkg:Frontend, tag:Design and UX, type:Enhancement

#523 Add binder configuration
  README.md
  binder/environment.yml
  binder/postBuild
Labels: tag:Documentation, type:Maintenance
