Repository jupyterlab/jupyterlab-git, pull requests merged in 2020-03, with the labels that each got.

#509 Improve history panel
  .gitignore
  src/components/GitPanel.tsx
  src/components/HistorySideBar.tsx
  src/components/PastCommitNode.tsx
  src/components/ResetDeleteSingleCommit.tsx
  src/components/SinglePastCommitInfo.tsx
  src/style/SinglePastCommitInfoStyle.ts
  src/style/common.ts
  tests/test-components/BranchMenu.spec.tsx
  tests/test-components/GitPanel.spec.tsx
  tests/test-components/HistorySideBar.spec.tsx
  tests/test-components/PastCommitNode.spec.tsx
  tests/test-components/Toolbar.spec.tsx
Labels: pkg:Frontend, status:Needs rebase, tag:Design and UX, type:Enhancement

#521 Enhance filelist
  src/components/ActionButton.tsx
  src/components/FileItem.tsx
  src/components/FileItemSimple.tsx
  src/components/FileList.tsx
  src/components/FilePath.tsx
  src/components/GitPanel.tsx
  src/components/GitStage.tsx
  src/components/GitStageSimple.tsx
  src/components/SinglePastCommitInfo.tsx
  src/model.ts
  src/style/ActionButtonStyle.ts
  src/style/FileItemStyle.ts
  src/style/FileListStyle.ts
  src/style/FilePathStyle.ts
  src/style/GitStageStyle.ts
  src/style/SinglePastCommitInfoStyle.ts
  src/style/icons.ts
  src/tokens.ts
  src/utils.ts
  style/images/checkmark-icon.svg
  style/images/diff-hover.svg
  style/images/discard-selected.svg
  style/images/discard.svg
  style/images/move-file-down-hover.svg
  style/images/move-file-down.svg
  style/images/move-file-up-hover.svg
  style/images/move-file-up.svg
  style/images/rewind-white.svg
  style/images/rewind.svg
  style/variables.css
  tests/test-components/FileItem.spec.tsx
Labels: pkg:Frontend, tag:Design and UX, type:Enhancement

#505 Add remote command
  jupyterlab_git/git.py
  jupyterlab_git/handlers.py
  jupyterlab_git/tests/test_remote.py
  src/gitMenuCommands.ts
  src/index.ts
  src/model.ts
  src/tokens.ts
  tests/commands.spec.tsx
Labels: pkg:Server Extension, status:Needs rebase, type:Enhancement

#558 add @web.authenticated to all handlers
  jupyterlab_git/handlers.py
Labels: pkg:Server Extension, tag:Auth and Security, type:Bug

#540 Document settings in the README
  README.md
Labels: status:Needs Review, tag:Documentation, type:Enhancement

#539 Add support for diffing all files
  jupyterlab_git/git.py
  jupyterlab_git/tests/test_handlers.py
  src/components/diff/PlainTextDiff.tsx
  tests/test-components/Diff.spec.tsx
Labels: status:Needs Review, type:Enhancement

#541 Add setting support for canceling a pull if merge conflict
  README.md
  jupyterlab_git/git.py
  jupyterlab_git/handlers.py
  jupyterlab_git/tests/test_clone.py
  jupyterlab_git/tests/test_pushpull.py
  schema/plugin.json
  src/model.ts
  src/tokens.ts
Labels: pkg:Server Extension, type:Enhancement

#569 Display message when server extension unavailable
  src/model.ts
Labels: pkg:Frontend, type:Enhancement

#536 Add default revert commit message and resizable commit message box
  src/components/CommitBox.tsx
  src/components/GitPanel.tsx
  src/components/HistorySideBar.tsx
  src/components/PastCommitNode.tsx
  src/components/ResetRevertDialog.tsx
  src/components/SinglePastCommitInfo.tsx
  src/model.ts
  src/style/ActionButtonStyle.ts
  src/style/CommitBox.ts
  src/style/FilePathStyle.ts
  src/style/PastCommitNode.ts
  src/style/PastCommitNodeStyle.ts
  src/style/ResetRevertDialog.ts
  src/style/SinglePastCommitInfo.ts
  src/tokens.ts
  style/diff-common.css
  tests/test-components/CommitBox.spec.tsx
  tests/test-components/HistorySideBar.spec.tsx
  tests/test-components/PastCommitNode.spec.tsx
Labels: status:Needs Review, type:Enhancement

#530 Add history to readme
  .all-contributorsrc
  README.md
  package.json
  yarn.lock
Labels: tag:Documentation, type:Enhancement

#571 Fix style of FileList and FileItem
  src/components/FileItem.tsx
  src/components/FileItemSimple.tsx
  src/components/FileList.tsx
  src/style/FileItemSimpleStyle.ts
  src/style/FileItemStyle.ts
  src/style/FileListStyle.ts
Labels: pkg:Frontend, tag:Design and UX, type:Bug

#573 Style improvement and fix
  .travis.yml
  src/components/SinglePastCommitInfo.tsx
  src/style/ActionButtonStyle.ts
  src/style/SinglePastCommitInfo.ts
Labels: pkg:Frontend, status:Needs Review, tag:Design and UX, type:Bug, type:Enhancement

#575 Fix status error on empty string
  jupyterlab_git/git.py
  jupyterlab_git/tests/test_status.py
Labels: pkg:Server Extension
