Repository jupyterlab/jupyterlab-git, pull requests merged in 2021-09, with the labels that each got.

#1032 Backport PR #1028 on branch 0.32.x (Fix Git History)
  jest.config.js
  src/commandsAndMenu.tsx
  src/model.ts
  tests/model.spec.tsx
Labels: bug

#1033 Backport PR #1022 on branch 0.32.x (Bump tar from 6.1.8 to 6.1.11)
  yarn.lock
Labels: tag:Dependencies

#1034 Backport PR #1021 on branch 0.32.x (Doubling click → double click)
  schema/plugin.json
Labels: enhancement
