Repository jupyterlab/jupyterlab-git, pull requests merged in 2022-12, with the labels that each got.

#1196 Update commandsAndMenu.tsx to replace "`" in file path for Open Git Repository since it leads to Command Injection Vulnerability
  src/commandsAndMenu.tsx
Labels: bug

#1184 Use preview tab for diff file views
  src/commandsAndMenu.tsx
  src/components/diff/PreviewMainAreaWidget.ts
  style/base.css
Labels: enhancement

#1204 Bump to 0.41.0
  package.json
Labels: maintenance
