Repository jupyterlab/jupyterlab-git, pull requests merged in 2022-09, with the labels that each got.

#1163 Add configuration to exclude paths
  README.md
  conftest.py
  jupyterlab_git/__init__.py
  jupyterlab_git/git.py
  jupyterlab_git/handlers.py
  jupyterlab_git/tests/test_handlers.py
Labels: enhancement

#1164 Bumping to 0.39.2
  package.json
Labels: maintenance

#1165 Raise error instead of set status
  jupyterlab_git/handlers.py
Labels: maintenance

#1172 fix: export logger instance for external use
  src/index.ts
Labels: bug
