Repository jupyterlab/jupyterlab-git, pull requests merged in 2023-10, with the labels that each got.

#1271 Add constrain in install instructions
  README.md
Labels: documentation

#1272 Show tags in history sidebar
  jupyterlab_git/git.py
  jupyterlab_git/handlers.py
  jupyterlab_git/tests/test_tag.py
  src/__tests__/test-components/HistorySideBar.spec.tsx
  src/__tests__/test-components/PastCommitNode.spec.tsx
  src/__tests__/test-components/TagMenu.spec.tsx
  src/components/GitPanel.tsx
  src/components/HistorySideBar.tsx
  src/components/NewTagDialog.tsx
  src/components/PastCommitNode.tsx
  src/components/TagMenu.tsx
  src/components/Toolbar.tsx
  src/model.ts
  src/tokens.ts
Labels: enhancement

#1277 Add context menu on commits in the HistorySidebar with add tag command
  src/commandsAndMenu.tsx
  src/components/HistorySideBar.tsx
  src/components/NewTagDialog.tsx
  src/components/PastCommitNode.tsx
  src/components/TagMenu.tsx
  src/tokens.ts
  ui-tests/tests/add-tag.spec.ts
Labels: enhancement

#1279 Push tags
  jupyterlab_git/git.py
  jupyterlab_git/tests/test_pushpull.py
Labels: enhancement

#1280 Fix stash REST API
  .github/workflows/pre-release.yml
  jupyterlab_git/git.py
  jupyterlab_git/handlers.py
  jupyterlab_git/tests/test_stash.py
  src/components/GitPanel.tsx
  src/components/GitStash.tsx
  src/model.ts
  src/tokens.ts
  ui-tests/tests/git-stash.spec.ts
Labels: enhancement

#1283 Fix commit message
  src/components/GitPanel.tsx
  ui-tests/tests/commit.spec.ts
Labels: bug

#1285 Remove drive from path.
  src/cloneCommand.tsx
  src/commandsAndMenu.tsx
  src/index.ts
Labels: bug
