Repository jupyterlab/jupyterlab-git, pull requests merged in 2023-11, with the labels that each got.

#1289 Fix styling
  src/components/CommitBox.tsx
  src/components/CommitMessage.tsx
  src/components/RebaseAction.tsx
  src/components/WarningBox.tsx
  src/style/CommitBox.ts
  src/style/GitPanel.ts
Labels: bug

#1290 Bump nbdime to rc0
  package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#1300 Lint README
  README.md
Labels: maintenance

#1299 Don't display details button if message is empty
  .github/workflows/build.yml
  README.md
  src/notifications.ts
  ui-tests/tests/merge-commit.spec.ts
Labels: bug

#1298 Load gitignore file (#1273)
  jupyterlab_git/git.py
  jupyterlab_git/handlers.py
  schema/plugin.json
  src/__tests__/commands.spec.tsx
  src/commandsAndMenu.tsx
  src/components/diff/PreviewMainAreaWidget.ts
  src/index.ts
  src/model.ts
  src/style/ActionButtonStyle.ts
  src/style/FileItemStyle.ts
  src/style/GitStageStyle.ts
  src/tokens.ts
  style/base.css
Labels: enhancement

#1302 Update nbdime to final release
  package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#1304 Fix testing `pathRepository` for `null`
  src/commandsAndMenu.tsx
  src/model.ts
Labels: bug

#1305 Update installation instruction
  README.md
Labels: documentation

#1306 Fix jitter in git panel
  CHANGELOG.md
  src/style/GitStageStyle.ts
  src/style/GitStashStyle.ts
Labels: bug
