Repository jupyterlab/jupyterlab-git, pull requests merged in 2023-06, with the labels that each got.

#1246 Fix menu entry selection
  ui-tests/tests/file-selection.spec.ts
Labels: bug

#1228 Add git stash
  jupyterlab_git/git.py
  jupyterlab_git/handlers.py
  jupyterlab_git/tests/test_stash.py
  src/commandsAndMenu.tsx
  src/components/FileList.tsx
  src/components/FilePath.tsx
  src/components/GitPanel.tsx
  src/components/GitStash.tsx
  src/model.ts
  src/style/FileListStyle.ts
  src/style/GitStashStyle.ts
  src/tokens.ts
  src/utils.ts
  tests/test-components/GitPanel.spec.tsx
  ui-tests/tests/data/test-repository-stash.tar.gz
  ui-tests/tests/git-stash.spec.ts
Labels: enhancement

#1223 Adding support for standalone diffs of images
  jupyterlab_git/git.py
  jupyterlab_git/tests/test_handlers.py
  package.json
  src/components/diff/ImageDiff.tsx
  src/index.ts
  src/style/ImageDiffStyle.ts
  ui-tests/tests/commit-diff.spec.ts
  ui-tests/tests/data/test-repository.tar.gz
  ui-tests/tests/image-diff.spec.ts
  ui-tests/tests/image-diff.spec.ts-snapshots/jpeg-diff-linux.png
  ui-tests/tests/image-diff.spec.ts-snapshots/png-diff-linux.png
  yarn.lock
Labels: enhancement

#1252 Fix linter error
  .prettierrc
  CHANGELOG.md
Labels: maintenance
