Repository jupyterlab/jupyterlab-git, pull requests merged in 2024-10, with the labels that each got.

#1360 Confirm identity validity
  src/components/GitPanel.tsx
Labels: bug

#1361 Add link to ignore
  .github/workflows/build.yml
Labels: maintenance

#1363 Create new branch in new repo
  jupyterlab_git/git.py
  jupyterlab_git/handlers.py
Labels: bug

#1364 Disable refresh button while refresh is in progress
  src/components/Toolbar.tsx
Labels: bug

#1365 Enable push/pull buttons for empty repos
  src/__tests__/test-components/Toolbar.spec.tsx
  src/components/Toolbar.tsx
Labels: bug

#1366 Add confirmation dialog when checking out remote branch
  src/components/BranchMenu.tsx
Labels: enhancement

#1370 Update the releaser workflows
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#1372 Revert "Publish 0.50.2"
  CHANGELOG.md
  package.json
  src/version.ts
Labels: maintenance

#1373 Add `publishConfig` to `package.json`
  package.json
Labels: maintenance
